#!/usr/bin/env node
'use strict';
// skill-map activity bridge (generated by `sm activity install`, v0.85.0).
// Contract: spec/provider-activity.md §Bridge contract. Do not edit;
// re-run the install command to regenerate.
//
// Invisibility invariants (HARD): always exit 0, stdout stays EMPTY,
// at most one short stderr line. Every failure path is a silent no-op,
// the provider runtime must never notice this hook exists.

const { readFileSync } = require('node:fs');
const { join, resolve } = require('node:path');

const LOOPBACK_HOSTS = new Set(['127.0.0.1', '::1', 'localhost']);
const TIMEOUT_MS = 1500;

// The bridge lives at <scopeRoot>/.skill-map/activity/bridge.js, so its
// OWN location identifies the project. Never derive the scope from the
// spawn cwd: runtimes disagree about it (Claude spawns hooks at the
// project root, Antigravity at the hook config's directory,
// live-verified 2026-07-04), and the bridge must work under all of them.
const SCOPE_ROOT = resolve(__dirname, '..', '..');

function main() {
  const provider = process.argv[2];
  if (!provider) return exitSilently();

  // 1. Discover the server. Missing / unparseable serve.json = no
  //    server (clean shutdown deletes it): silent no-op.
  let info;
  try {
    info = JSON.parse(readFileSync(join(SCOPE_ROOT, '.skill-map', 'serve.json'), 'utf8'));
  } catch {
    return exitSilently();
  }

  // 2. Scope check: a hook firing in project A must never reach
  //    project B's server. The bridge's own installed location is the
  //    project identity; serve.json must agree.
  if (typeof info.scopeRoot !== 'string' || resolve(info.scopeRoot) !== SCOPE_ROOT) {
    return exitSilently();
  }

  // 3. Loopback check: a tampered serve.json must not exfiltrate the
  //    (privacy-sensitive) event to a remote host.
  if (typeof info.host !== 'string' || !LOOPBACK_HOSTS.has(info.host.toLowerCase())) {
    return exitSilently();
  }

  // 3b. Port sanity: serve.json is disk state a tampered clone can
  //     rewrite. The host is already pinned to loopback, so the blast
  //     radius is another local port, but a non-integer / out-of-range
  //     value has no legitimate reading; refuse it rather than
  //     interpolate it into the request URL.
  if (!Number.isInteger(info.port) || info.port < 1 || info.port > 65535) {
    return exitSilently();
  }

  // 4. Forward the raw event verbatim.
  let raw = '';
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', (chunk) => {
    raw += chunk;
  });
  process.stdin.on('end', () => {
    void forward(provider, info, raw);
  });
}

async function forward(provider, info, raw) {
  let event;
  try {
    event = JSON.parse(raw);
  } catch {
    return exitSilently();
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    await fetch('http://' + info.host + ':' + info.port + '/api/activity', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-skill-map-token': typeof info.token === 'string' ? info.token : '',
      },
      body: JSON.stringify({ provider, event }),
      signal: controller.signal,
    });
  } catch {
    // serve.json exists but the server is unreachable: a crashed server
    // left a stale file behind. One short warning (stderr only), then
    // the mandatory silent exit.
    process.stderr.write('skill-map activity bridge: server unreachable (stale serve.json?)\n');
  } finally {
    clearTimeout(timer);
  }
  exitSilently();
}

function exitSilently() {
  process.exit(0);
}

main();
