/**
 * The activity-bridge artifact `sm activity install <provider>` writes
 * to `.skill-map/activity/bridge.js` (see `spec/provider-activity.md`
 * §Bridge contract).
 *
 * The bridge is the ONLY piece that runs inside the provider's hook
 * pipeline, so its contract is stricter than any other code we ship:
 *
 *   - **Invisible (HARD)**: always exit `0`, always keep stdout EMPTY,
 *     at most one short stderr warning. Provider runtimes interpret
 *     hook exit codes and stdout as control flow (a non-zero exit can
 *     BLOCK the operator's tool call); every failure path is a silent
 *     no-op.
 *   - **Dumb**: zero mapping logic. It discovers the server via
 *     `serve.json`, checks scope + loopback, forwards raw stdin, done.
 *     All payload knowledge stays in the Provider's `mapEvent`.
 *   - **Zero-dependency CommonJS**: plain `.js` on Node built-ins only
 *     (`node:fs` + global `fetch`), no install step. Because a bare
 *     `.js` inherits the NEAREST `package.json`'s `type` (an ESM host
 *     project would break `require`), the installer writes a sibling
 *     `package.json` pinning `{"type":"commonjs"}` next to the bridge,
 *     so it parses as CommonJS regardless of the host project.
 *
 * The template is a source STRING (not a bundled asset) so the CLI can
 * write it anywhere and tests can exercise the exact bytes users get.
 * `{{SM_VERSION}}` is stamped at install time for debuggability.
 */

import { VERSION } from '../../version.js';

/** Fetch abort window: a hung server must never hold the hook open. */
const BRIDGE_TIMEOUT_MS = 1500;

const BRIDGE_TEMPLATE = `#!/usr/bin/env node
'use strict';
// skill-map activity bridge (generated by \`sm activity install\`, v{{SM_VERSION}}).
// Contract: spec/provider-activity.md §Bridge contract. Do not edit;
// re-run the install command to regenerate.
//
// Invisibility invariants (HARD): always exit 0, stdout stays EMPTY,
// at most one short stderr line. Every failure path is a silent no-op,
// the provider runtime must never notice this hook exists.

const { readFileSync } = require('node:fs');
const { join, resolve } = require('node:path');

const LOOPBACK_HOSTS = new Set(['127.0.0.1', '::1', 'localhost']);
const TIMEOUT_MS = ${BRIDGE_TIMEOUT_MS};

// The bridge lives at <scopeRoot>/.skill-map/activity/bridge.js, so its
// OWN location identifies the project. Never derive the scope from the
// spawn cwd: runtimes disagree about it (Claude spawns hooks at the
// project root, Antigravity at the hook config's directory,
// live-verified 2026-07-04), and the bridge must work under all of them.
const SCOPE_ROOT = resolve(__dirname, '..', '..');

function main() {
  const provider = process.argv[2];
  if (!provider) return exitSilently();

  // 1. Discover the server. Missing / unparseable serve.json = no
  //    server (clean shutdown deletes it): silent no-op.
  let info;
  try {
    info = JSON.parse(readFileSync(join(SCOPE_ROOT, '.skill-map', 'serve.json'), 'utf8'));
  } catch {
    return exitSilently();
  }

  // 2. Scope check: a hook firing in project A must never reach
  //    project B's server. The bridge's own installed location is the
  //    project identity; serve.json must agree.
  if (typeof info.scopeRoot !== 'string' || resolve(info.scopeRoot) !== SCOPE_ROOT) {
    return exitSilently();
  }

  // 3. Loopback check: a tampered serve.json must not exfiltrate the
  //    (privacy-sensitive) event to a remote host.
  if (typeof info.host !== 'string' || !LOOPBACK_HOSTS.has(info.host.toLowerCase())) {
    return exitSilently();
  }

  // 3b. Port sanity: serve.json is disk state a tampered clone can
  //     rewrite. The host is already pinned to loopback, so the blast
  //     radius is another local port, but a non-integer / out-of-range
  //     value has no legitimate reading; refuse it rather than
  //     interpolate it into the request URL.
  if (!Number.isInteger(info.port) || info.port < 1 || info.port > 65535) {
    return exitSilently();
  }

  // 4. Forward the raw event verbatim.
  let raw = '';
  process.stdin.setEncoding('utf8');
  process.stdin.on('data', (chunk) => {
    raw += chunk;
  });
  process.stdin.on('end', () => {
    void forward(provider, info, raw);
  });
}

async function forward(provider, info, raw) {
  let event;
  try {
    event = JSON.parse(raw);
  } catch {
    return exitSilently();
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    await fetch('http://' + info.host + ':' + info.port + '/api/activity', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-skill-map-token': typeof info.token === 'string' ? info.token : '',
      },
      body: JSON.stringify({ provider, event }),
      signal: controller.signal,
    });
  } catch {
    // serve.json exists but the server is unreachable: a crashed server
    // left a stale file behind. One short warning (stderr only), then
    // the mandatory silent exit.
    process.stderr.write('skill-map activity bridge: server unreachable (stale serve.json?)\\n');
  } finally {
    clearTimeout(timer);
  }
  exitSilently();
}

function exitSilently() {
  process.exit(0);
}

main();
`;

/** The exact bridge source `sm activity install` writes. */
export function renderActivityBridge(): string {
  return BRIDGE_TEMPLATE.replace('{{SM_VERSION}}', VERSION);
}

/**
 * Sibling `package.json` written next to the bridge. Pins the module
 * type so the `.js` bridge parses as CommonJS even when the host
 * project's own `package.json` declares `"type": "module"` (where a
 * bare `.js` would otherwise be ESM and `require` would throw).
 */
export const BRIDGE_PACKAGE_JSON = '{\n  "type": "commonjs"\n}\n';
