/**
 * ENVELOPE of the in-process activity plugin `sm activity install
 * <provider>` writes for `plugin-file` providers (see
 * `spec/provider-activity.md` §The `provider.activity` capability,
 * plugin-file paragraph).
 *
 * The generated file is the in-process analog of the spawned bridge,
 * and its source splits along the capability's ownership line:
 *
 *   - **This module owns the ENVELOPE**, the invariants every
 *     plugin-file provider upholds regardless of runtime:
 *     - **Invisible (HARD)**: hook callbacks NEVER throw (an exception
 *       inside an in-process hook can alter or block the host session,
 *       the analog of a non-zero exit). Every failure path is a silent
 *       no-op; there is no stdout/stderr surface at all.
 *     - **Same discovery as the bridge**: `<directory>/.skill-map/serve.json`
 *       read per event (the plugin context's `directory` IS the project
 *       root), scope + loopback + token checks, 1500ms abort, fail-open.
 *   - **The Provider owns the HOOK REGISTRATIONS**
 *     (`IProviderActivityAdapter.pluginHooksSource`, spliced at
 *     `{{HOOKS}}`): which of ITS runtime's hooks to register, the
 *     wiring-level filters that keep the host's high-frequency traffic
 *     from ever leaving the process, and the `{ hook, directory, ... }`
 *     wrapper each registration forwards. All payload knowledge stays
 *     provider-side, mirroring `mapEvent`; this module never names
 *     another runtime's hooks.
 *
 * The template is a source STRING (not a bundled asset) so the CLI can
 * write it anywhere and tests can exercise the exact bytes users get.
 * `{{SM_VERSION}}` is stamped at install time; the header line doubles
 * as the ownership marker install/uninstall/status recognise.
 */

import { SKILL_MAP_DIR } from '../../kernel/util/skill-map-paths.js';
import { SERVE_INFO_FILENAME } from '../paths/db-path.js';
import { VERSION } from '../../version.js';

/** Fetch abort window: a hung server must never hold the host's hook open. */
const PLUGIN_TIMEOUT_MS = 1500;

/** Header marker the engine uses to recognise the file as skill-map's own. */
export const ACTIVITY_PLUGIN_MARKER = 'skill-map activity plugin';

const PLUGIN_TEMPLATE = `// ${ACTIVITY_PLUGIN_MARKER} (generated by \`sm activity install\`, v{{SM_VERSION}}).
// Contract: spec/provider-activity.md §Bridge contract (in-process form).
// Do not edit; re-run the install command to regenerate.
//
// Invariants (HARD): hook callbacks never throw, every failure path is
// a silent no-op, nothing beyond the wrapped raw event leaves the
// process, and only the loopback server named by the project's own
// serve.json is ever contacted.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const LOOPBACK_HOSTS = new Set(['127.0.0.1', '::1', 'localhost']);
const TIMEOUT_MS = ${PLUGIN_TIMEOUT_MS};
const PROVIDER = '{{PROVIDER_ID}}';

export const SkillMapActivity = async ({ directory, serverUrl }) => {
  const root = typeof directory === 'string' && directory.length > 0 ? directory : null;
  // The runtime's OWN local API base, when its plugin input exposes it
  // (OpenCode's does). Registered as the agent-doorbell wake endpoint
  // (spec/job-lifecycle.md §Agent doorbell): once at load, and refreshed
  // on every forwarded event so a restarted server relearns it.
  const agentEndpoint = (() => {
    try {
      const value = serverUrl === undefined || serverUrl === null ? '' : String(serverUrl);
      return value.startsWith('http') ? value : null;
    } catch {
      return null;
    }
  })();

  function discover() {
    if (root === null) return null;
    const info = JSON.parse(readFileSync(join(root, '${SKILL_MAP_DIR}', '${SERVE_INFO_FILENAME}'), 'utf8'));
    if (typeof info.scopeRoot !== 'string' || info.scopeRoot !== root) return null;
    if (typeof info.host !== 'string' || !LOOPBACK_HOSTS.has(info.host.toLowerCase())) return null;
    // Port sanity: refuse a tampered serve.json port rather than
    // interpolate a non-integer / out-of-range value into the URL
    // (host is already pinned to loopback above).
    if (!Number.isInteger(info.port) || info.port < 1 || info.port > 65535) return null;
    return info;
  }

  async function post(info, path, body) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      await fetch('http://' + info.host + ':' + info.port + path, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'x-skill-map-token': typeof info.token === 'string' ? info.token : '',
        },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timer);
    }
  }

  async function forward(hook, payload) {
    try {
      const info = discover();
      if (info === null) return;
      const body = { provider: PROVIDER, event: { hook, directory: root, ...payload } };
      if (agentEndpoint !== null) body.agentEndpoint = agentEndpoint;
      await post(info, '/api/activity', body);
    } catch {
      // Silent no-op: no server, stale serve.json, unreachable host.
    }
  }

  // One doorbell registration at load (fire-and-forget, silent): covers
  // the idle session that never fires a hook before a job is queued.
  try {
    const info = discover();
    if (info !== null && agentEndpoint !== null) {
      void post(info, '/api/agent/doorbell', { url: agentEndpoint }).catch(() => {});
    }
  } catch {
    // Silent no-op, same posture as forward().
  }

  return {
{{HOOKS}}
  };
};
`;

/**
 * The exact plugin source `sm activity install` writes for `providerId`:
 * the shared envelope with the provider's own hook registrations
 * (`IProviderActivityAdapter.pluginHooksSource`) spliced in.
 */
export function renderActivityPlugin(providerId: string, hooksSource: string): string {
  return PLUGIN_TEMPLATE.replace('{{SM_VERSION}}', VERSION)
    .replace('{{PROVIDER_ID}}', providerId)
    .replace('{{HOOKS}}', hooksSource);
}

/**
 * Sibling `package.json` written next to the installed plugin file. The
 * rendered plugin is an ES module (`export const SkillMapActivity`), so
 * this pins `"type": "module"` for the plugin dir, otherwise Node (via
 * the vendor's plugin loader) treats a bare `.js` as CommonJS whenever
 * the host project's `package.json` is absent or `"type": "commonjs"`,
 * emitting `MODULE_TYPELESS_PACKAGE_JSON` (or throwing on `export`). The
 * CommonJS analogue for the spawned bridge is `BRIDGE_PACKAGE_JSON`. The
 * installer writes this only when the plugin dir has no `package.json`
 * (the dir is the vendor's territory, shared with its other plugins), so
 * a vendor-authored one is never clobbered.
 */
export const ACTIVITY_PLUGIN_PACKAGE_JSON = '{\n  "type": "module"\n}\n';
