// AUTO-GENERATED by scripts/generate-view-catalog.js. Do not edit by hand.
// Regenerate with `pnpm --filter @skill-map/cli view-catalog`.
// Source of truth: the `oneOf` const lists in
//   spec/schemas/view-slots.schema.json#/$defs/SlotName
//   spec/schemas/input-types.schema.json#/$defs/InputTypeName

/**
 * Closed enum of view slot names. Mirror of
 * `spec/schemas/view-slots.schema.json#/$defs/SlotName`.
 */
export type TSlotName =
  | 'card.title.right'
  | 'card.subtitle.left'
  | 'card.footer.left'
  | 'card.footer.right'
  | 'graph.node.alert'
  | 'inspector.header.badge'
  | 'inspector.action.button'
  | 'inspector.body.panel.breakdown'
  | 'inspector.body.panel.records'
  | 'inspector.body.panel.tree'
  | 'inspector.body.panel.key-values'
  | 'inspector.body.panel.link-list'
  | 'inspector.body.panel.markdown'
  | 'topbar.nav.start';

/**
 * Runtime mirror of `TSlotName`. Single source of truth for every
 * consumer that compares an untrusted string against the closed
 * catalog at runtime (manifest validation, `sm plugins doctor` drift
 * checks, `ctx.emitContribution` payload routing).
 */
export const ALL_SLOT_NAMES: ReadonlyArray<TSlotName> = [
  'card.title.right',
  'card.subtitle.left',
  'card.footer.left',
  'card.footer.right',
  'graph.node.alert',
  'inspector.header.badge',
  'inspector.action.button',
  'inspector.body.panel.breakdown',
  'inspector.body.panel.records',
  'inspector.body.panel.tree',
  'inspector.body.panel.key-values',
  'inspector.body.panel.link-list',
  'inspector.body.panel.markdown',
  'topbar.nav.start',
];

/**
 * Set form of `ALL_SLOT_NAMES` for O(1) membership checks. Typed as
 * `ReadonlySet<string>` (not `ReadonlySet<TSlotName>`) because callers
 * feed it untrusted strings pulled from plugin manifests.
 */
export const KNOWN_SLOT_NAMES: ReadonlySet<string> = new Set(ALL_SLOT_NAMES);

/**
 * Closed enum of input-type names for plugin settings. Mirror of
 * `spec/schemas/input-types.schema.json#/$defs/InputTypeName`.
 */
export type TInputTypeName =
  | 'string-list'
  | 'single-string'
  | 'boolean-flag'
  | 'integer'
  | 'enum-pick'
  | 'enum-multipick'
  | 'path-glob'
  | 'regex'
  | 'secret'
  | 'key-value-list';

/** Runtime mirror of `TInputTypeName`. */
export const ALL_INPUT_TYPE_NAMES: ReadonlyArray<TInputTypeName> = [
  'string-list',
  'single-string',
  'boolean-flag',
  'integer',
  'enum-pick',
  'enum-multipick',
  'path-glob',
  'regex',
  'secret',
  'key-value-list',
];
