/* eslint-disable */
// AUTO-GENERATED by scripts/generate-view-catalog.js. Do not edit by hand.
// Regenerate with `pnpm --filter @skill-map/cli view-catalog`.
// Source of truth: the `oneOf` const lists in
//   spec/schemas/view-slots.schema.json#/$defs/SlotName
//   spec/schemas/input-types.schema.json#/$defs/InputTypeName

/**
 * Closed enum of view slot names. Mirror of
 * `spec/schemas/view-slots.schema.json#/$defs/SlotName`.
 */
export type TSlotName =
  | 'card.title.right'
  | 'card.subtitle.left'
  | 'card.footer.left'
  | 'card.footer.right'
  | 'graph.node.alert'
  | 'inspector.header.badge'
  | 'inspector.action.button'
  | 'inspector.body.panel.breakdown'
  | 'inspector.body.panel.records'
  | 'inspector.body.panel.tree'
  | 'inspector.body.panel.key-values'
  | 'inspector.body.panel.link-list'
  | 'inspector.body.panel.markdown'
  | 'topbar.nav.start';

/**
 * Runtime mirror of `TSlotName`. Single source of truth for every
 * consumer that compares an untrusted string against the closed
 * catalog at runtime (manifest validation, `sm plugins doctor` drift
 * checks, `ctx.emitContribution` payload routing).
 */
export const ALL_SLOT_NAMES: ReadonlyArray<TSlotName> = [
  'card.title.right',
  'card.subtitle.left',
  'card.footer.left',
  'card.footer.right',
  'graph.node.alert',
  'inspector.header.badge',
  'inspector.action.button',
  'inspector.body.panel.breakdown',
  'inspector.body.panel.records',
  'inspector.body.panel.tree',
  'inspector.body.panel.key-values',
  'inspector.body.panel.link-list',
  'inspector.body.panel.markdown',
  'topbar.nav.start',
];

/**
 * Set form of `ALL_SLOT_NAMES` for O(1) membership checks. Typed as
 * `ReadonlySet<string>` (not `ReadonlySet<TSlotName>`) because callers
 * feed it untrusted strings pulled from plugin manifests.
 */
export const KNOWN_SLOT_NAMES: ReadonlySet<string> = new Set(ALL_SLOT_NAMES);

/**
 * Closed enum of input-type names for plugin settings. Mirror of
 * `spec/schemas/input-types.schema.json#/$defs/InputTypeName`.
 */
export type TInputTypeName =
  | 'string-list'
  | 'single-string'
  | 'boolean-flag'
  | 'integer'
  | 'number'
  | 'enum-pick'
  | 'enum-multipick'
  | 'path-glob'
  | 'regex'
  | 'secret'
  | 'key-value-list';

/** Runtime mirror of `TInputTypeName`. */
export const ALL_INPUT_TYPE_NAMES: ReadonlyArray<TInputTypeName> = [
  'string-list',
  'single-string',
  'boolean-flag',
  'integer',
  'number',
  'enum-pick',
  'enum-multipick',
  'path-glob',
  'regex',
  'secret',
  'key-value-list',
];

// ---------------------------------------------------------------------------
// Per-slot payload types, generated from
// `view-slots.schema.json#/$defs/payloads`. TS captures the STRUCTURAL shape
// only; array length caps (maxItems) and "at least one of" (anyOf) constraints
// are enforced at runtime by AJV (see kernel/adapters/schema-validators.ts).
// ---------------------------------------------------------------------------
/**
 * Closed severity palette aligned with PrimeNG `<p-tag>` / `<p-message>` severities. Used by counter, tag, alert, and icon slots for color/contrast hints. The UI maps each severity to a theme-aware tint; plugins do not pick raw colors.
 */
export type Severity = 'info' | 'warn' | 'success' | 'danger';
/**
 * Single string, prefix-discriminated by the UI. Four valid shapes: (1) emoji, any value starting with a non-ASCII-letter codepoint renders as text; (2) PrimeIcons, `pi-foo` or `pi pi-foo` renders as `<i class="pi pi-foo">`; (3) FontAwesome explicit family, `fa-solid fa-foo` / `fa-regular fa-foo` / `fa-brands fa-foo` passes through as-is; (4) FontAwesome shorthand, `fa-foo` (no family token) defaults to `fa-solid fa-foo`. Bare class names without a `pi-` / `fa-` prefix are rejected at manifest load (invalid-manifest). Unknown PrimeIcons / FontAwesome names render no icon (silent fallback) plus a console warning.
 */
export type IconString = string;

export interface SlotPayloadMap {
  'card.title.right': IconMarkerPayload;
  'card.subtitle.left': CounterPayload;
  'card.footer.left': CounterPayload;
  'card.footer.right': CounterPayload;
  'graph.node.alert': AlertPayload;
  'inspector.header.badge': BadgePayload;
  'inspector.action.button': ActionButtonPayload;
  'inspector.body.panel.breakdown': BreakdownPayload;
  'inspector.body.panel.records': RecordsPayload;
  'inspector.body.panel.tree': TreeNode;
  'inspector.body.panel.key-values': KeyValuesPayload;
  'inspector.body.panel.link-list': LinkListPayload;
  'inspector.body.panel.markdown': MarkdownPayload;
  'topbar.nav.start': ScopeStatPayload;
}
/**
 * Single icon per node, small standalone marker rendered next to the card title. The manifest requires `icon`; the payload optionally overrides it per node and may add `severity` (color tint) and `tooltip`. No counts, no labels, for chip + number use a counter slot; for label + severity use a tag slot. 'Empty' for `emitWhenEmpty` is the absence of both payload `icon` and a manifest fallback (in practice never empty since the manifest icon is required).
 */
export interface IconMarkerPayload {
  /**
   * Single string, prefix-discriminated by the UI. Four valid shapes: (1) emoji, any value starting with a non-ASCII-letter codepoint renders as text; (2) PrimeIcons, `pi-foo` or `pi pi-foo` renders as `<i class="pi pi-foo">`; (3) FontAwesome explicit family, `fa-solid fa-foo` / `fa-regular fa-foo` / `fa-brands fa-foo` passes through as-is; (4) FontAwesome shorthand, `fa-foo` (no family token) defaults to `fa-solid fa-foo`. Bare class names without a `pi-` / `fa-` prefix are rejected at manifest load (invalid-manifest). Unknown PrimeIcons / FontAwesome names render no icon (silent fallback) plus a console warning.
   */
  icon?: string;
  severity?: Severity;
  tooltip?: string;
}
/**
 * Single icon + integer pair, modelled after the `.sm-gnode__stat` rows in the card footer. Manifest requires `icon` (enforced by `IViewContribution.allOf` for every counter slot); payload carries `value`, optionally `severity` and `tooltip`. The manifest `label` is metadata (docs / plugin-doctor / aria-label) and is NOT rendered inline.
 */
export interface CounterPayload {
  /**
   * Single non-negative integer for the chip / badge. 'Empty' for `emitWhenEmpty` purposes is `value === 0`.
   */
  value: number;
  tooltip?: string;
  /**
   * Closed severity palette aligned with PrimeNG `<p-tag>` / `<p-message>` severities. Used by counter, tag, alert, and icon slots for color/contrast hints. The UI maps each severity to a theme-aware tint; plugins do not pick raw colors.
   */
  severity?: 'info' | 'warn' | 'success' | 'danger';
}
/**
 * Decoration on the graph node (corner badge / pin). At least one of `icon`, `severity`, `count` is required. 'Empty' for `emitWhenEmpty` is the absence of `icon` AND `count`. Hard cap 1 marker per node per plugin extension (slot config enforces).
 */
export interface AlertPayload {
  icon?: IconString;
  severity?: Severity;
  /**
   * Optional badge count rendered next to the icon (1-99; 99+ collapses to '99+'). Omit for an icon-only marker.
   */
  count?: number;
  tooltip?: string;
}
/**
 * Unified inspector header badge. At least one of `icon`, `label`, `count` is required; optional `severity` tint and `tooltip`. Multi-cardinality slot (priority order, modeled on card.footer.left); a plugin extension may emit several. 'Empty' for `emitWhenEmpty` is the absence of `icon` AND `label` AND `count`. Replaces the retired `_counter`/`_tag` header sub-slots: a counter-style badge sets `count` (+`icon`), a tag-style badge sets `label` (+`severity`), the stale clock sets `icon` + `tooltip`.
 */
export interface BadgePayload {
  icon?: IconString;
  label?: string;
  count?: number;
  severity?: Severity;
  tooltip?: string;
}
/**
 * An action button rendered in the inspector. The manifest declares only `{ slot: 'inspector.action.button' }`; the per-node payload carries the action id, label, and the dynamic `enabled` flag. Click dispatches the Action via POST /api/actions/:id. `emitWhenEmpty` does not apply (a button is always meaningful). A payload carrying `surface` is not rendered as a button at all: it re-homes onto the named UI surface instead (see `surface`).
 */
export interface ActionButtonPayload {
  /**
   * Qualified Action id `<plugin>/<action>` the click dispatches via POST /api/actions/:id. Resolved by the kernel registry; an unknown id makes the BFF answer 404.
   */
  actionId: string;
  label: string;
  icon?: IconString;
  severity?: Severity;
  /**
   * Dynamic gate. The button is ALWAYS emitted (the persistence upsert refreshes the row each scan); `false` renders it disabled. e.g. `isStale` for the bump button.
   */
  enabled: boolean;
  /**
   * Tooltip shown when `enabled` is false.
   */
  disabledReason?: string;
  /**
   * Reserved (Step 2+). Static input merged into the dispatch body for parametrized actions that need no user prompt.
   */
  input?: {};
  prompt?: ActionPrompt;
  /**
   * Reserved. Require an extra confirm step before dispatch (destructive actions).
   */
  confirm?: boolean;
  /**
   * Re-homed affordance declaration: instead of rendering as a generic button in the inspector Actions section, this contribution IS the named UI surface (the header version chip, the header stability chip, the inline tag row and its card twins). The UI selects re-homed contributions by THIS field and dispatches the payload's `actionId`; it never matches extension ids, so any plugin may claim a surface and a disabled extension removes it. A declared surface excludes the contribution from the generic Actions section. At most one contribution per node should claim a given surface; when several do, the UI uses the first by contribution priority order.
   */
  surface?: 'version' | 'stability' | 'tags';
}
/**
 * Reserved (Step 3+). Declares an input-type prompt the UI collects before dispatching (enum-pick for stability, single-string for tags).
 */
export interface ActionPrompt {
  /**
   * Input-type id from the closed catalog. The UI renders the matching control before dispatch (`single-string`, `enum-pick` and `string-list` today; other types degrade to a graceful 'unsupported' notice).
   */
  inputType: (
    | 'string-list'
    | 'single-string'
    | 'boolean-flag'
    | 'integer'
    | 'number'
    | 'enum-pick'
    | 'enum-multipick'
    | 'path-glob'
    | 'regex'
    | 'secret'
    | 'key-value-list'
  ) &
    string;
  /**
   * Key under which the collected value is placed in the dispatch `input` body.
   */
  paramKey: string;
  label: string;
  /**
   * Optional pre-filled value the UI seeds the control with before the user edits (e.g. a node's current tags for a `string-list` edit). String for scalar input-types, string array for list input-types.
   */
  defaultValue?: string | string[];
  /**
   * Choice list for `enum-pick` / `enum-multipick` input types.
   */
  options?: {
    value: string;
    label: string;
  }[];
}
export interface BreakdownPayload {
  /**
   * Top-N labeled values rendered as a horizontal bar chart. Hard cap 20 bars (overflow rejected at validation, plugin should pre-truncate). 'Empty' for `emitWhenEmpty` is `bars.length === 0`.
   *
   * @maxItems 20
   */
  bars: {
    label: string;
    value: number;
    tooltip?: string;
  }[];
}
export interface RecordsPayload {
  /**
   * Column declarations (max 6). Each row's value at `key` is rendered under `label`.
   *
   * @minItems 1
   * @maxItems 6
   */
  columns: {
    key: string;
    label: string;
  }[];
  /**
   * Tabular rows (max 50). Cell values are scalar only (string ≤256 chars, number, boolean, or null). 'Empty' for `emitWhenEmpty` is `rows.length === 0`.
   *
   * @maxItems 50
   */
  rows: {
    [k: string]: string | number | boolean | null;
  }[];
}
/**
 * Recursive tree rendered as an indented hierarchy. Hard caps: max depth 6, max 200 total nodes per tree (validator enforces). 'Empty' for `emitWhenEmpty` is the root having no `children`.
 */
export interface TreeNode {
  label: string;
  marker?: IconString;
  tooltip?: string;
  children?: TreeNode1[];
}
export interface TreeNode1 {
  label: string;
  marker?: IconString;
  tooltip?: string;
  children?: TreeNode1[];
}
export interface KeyValuesPayload {
  /**
   * Flat key/value pairs (max 50). Renders as a definition list. 'Empty' for `emitWhenEmpty` is `pairs.length === 0`.
   *
   * @maxItems 50
   */
  pairs: {
    key: string;
    value: string | number | boolean | null;
    tooltip?: string;
  }[];
}
export interface LinkListPayload {
  /**
   * List of in-scope node paths (max 100). 'Empty' for `emitWhenEmpty` is `links.length === 0`.
   *
   * @maxItems 100
   */
  links: {
    /**
     * Node path within the scope. Resolved by the UI to a clickable link via `Router.navigate`, never rendered as a raw `[href]` (per the renderer attr-sanitization analyzer).
     */
    path: string;
    label?: string;
    /**
     * Optional Provider kind id (informational). The UI may apply per-kind tinting from `kindRegistry`.
     */
    kind?: string;
  }[];
}
export interface MarkdownPayload {
  /**
   * Markdown text rendered with a sanitized allow-list (paragraphs, headings up to H3, lists, inline code, fenced code, emphasis, strong, blockquote). HTML, scripts, embedded SVG, image tags, and link autodetection are stripped. Hard cap 4096 chars to keep render cost bounded. 'Empty' for `emitWhenEmpty` is `markdown.trim() === ''`.
   */
  markdown: string;
}
/**
 * Single value summarizing the entire scope. Emitted ONCE per scan (not per node). Plugins use `ctx.emitScopeContribution(...)` (analyzer context), extractors do not see `emitScopeContribution`.
 */
export interface ScopeStatPayload {
  /**
   * Either a non-negative integer or a short string. The UI renders it as a single chip in the topbar.
   */
  value: number | string;
  label?: string;
  tooltip?: string;
  severity?: Severity;
}

/**
 * Payload type for a given slot. `ctx.emitContribution` infers this from the
 * declared contribution's `slot`, so the author gets a typed payload argument.
 */
export type SlotPayload<S extends TSlotName> = SlotPayloadMap[S];
