/**
 * Action stub generator. Emits TWO files (structure-as-truth): the
 * `index.js` with the `invoke()` body and a sibling `report.schema.json`
 * that every Action must carry. Deterministic, so NO `prompt.md` (a
 * deterministic Action with a prompt template fails to load).
 */

import type { IKindGenerator, IScaffoldFile } from './types.js';

function indexStub(extId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the invoke() body.
 *
 * Loader contract: default export object literal; \`kind\` (action) and id
 * (\`${extId}\`) come from the folder layout (structure-as-truth), so
 * neither is declared here. Every Action carries a sibling
 * \`report.schema.json\`; a deterministic Action must NOT carry a
 * \`prompt.md\` (that is the probabilistic surface).
 *
 * \`invoke(input, ctx)\` returns \`{ report, writes? }\`. The report must
 * match this folder's \`report.schema.json\` (which extends the shared
 * report-base: \`confidence\` + \`safety\`). \`writes\` is an optional
 * array of side-effect descriptors the kernel materialises after the
 * call returns (e.g. a sidecar write); keep \`invoke()\` itself pure.
 *
 * See: spec/plugin-author-guide.md, spec/schemas/extensions/action.schema.json
 */
export default {
  version: '0.1.0',
  description: 'Demo deterministic action; returns a fixed report.',
  mode: 'deterministic',

  invoke(input, ctx) {
    return {
      report: {
        ok: true,
        confidence: 1,
        safety: { injectionDetected: false, contentQuality: 'unknown' },
      },
    };
  },
};
`;
}

function reportSchema(pluginId: string, extId: string): string {
  const schema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `urn:skill-map:${pluginId}/${extId}/report`,
    title: 'DemoReport',
    description:
      'Report returned by the demo action. Deterministic: confidence is fixed at 1 and no injection is detected.',
    type: 'object',
    required: ['confidence', 'safety'],
    additionalProperties: false,
    properties: {
      ok: { type: 'boolean' },
      confidence: { type: 'number', minimum: 0, maximum: 1 },
      safety: {
        type: 'object',
        required: ['injectionDetected', 'contentQuality'],
        additionalProperties: false,
        properties: {
          injectionDetected: { type: 'boolean' },
          contentQuality: {
            type: 'string',
            enum: ['high', 'medium', 'low', 'unknown'],
          },
        },
      },
    },
  };
  return JSON.stringify(schema, null, 2) + '\n';
}

export const actionGenerator: IKindGenerator = {
  folder: 'actions',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-action`;
    return [
      { relPath: `actions/${ext}/index.js`, contents: indexStub(ext) },
      { relPath: `actions/${ext}/report.schema.json`, contents: reportSchema(pluginId, ext) },
    ];
  },
};
