/**
 * Analyzer stub generator. Emits a deterministic analyzer that walks the
 * scanned graph and returns `Issue[]`. The demo flags isolated nodes (no
 * links in or out) as `info`. The kernel stamps `analyzerId` from the
 * folder-derived id, so the returned issues omit it.
 */

import type { IKindGenerator, IScaffoldFile } from './types.js';

function stub(extId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the evaluate() body.
 *
 * Loader contract: default export object literal; \`kind\` (analyzer) and
 * id (\`${extId}\`) come from the folder layout (structure-as-truth), so
 * neither is declared here. Re-declaring them is \`invalid-manifest\`.
 *
 * \`evaluate(ctx)\` runs once per scan and returns \`Issue[]\`. The kernel
 * stamps \`analyzerId\` from this extension's id and validates each issue
 * (\`severity\` must be 'error' | 'warn' | 'info'; off-spec issues drop
 * with an \`extension.error\` diagnostic). \`ctx.nodes\` / \`ctx.links\`
 * are the scanned graph; \`ctx.accumulatedIssues\` is the live issue
 * accumulator (read-only) for late-phase aggregate analyzers.
 *
 * See: spec/plugin-author-guide.md, spec/schemas/extensions/analyzer.schema.json
 */
export default {
  version: '0.1.0',
  description: 'Flags nodes that have no inbound or outbound links.',
  mode: 'deterministic',

  evaluate(ctx) {
    const issues = [];
    for (const node of ctx.nodes) {
      if (node.linksInCount === 0 && node.linksOutCount === 0) {
        issues.push({
          severity: 'info',
          nodeIds: [node.path],
          message: 'Node has no links in or out (isolated).',
        });
      }
    }
    return issues;
  },
};
`;
}

export const analyzerGenerator: IKindGenerator = {
  folder: 'analyzers',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-analyzer`;
    return [{ relPath: `analyzers/${ext}/index.js`, contents: stub(ext) }];
  },
};
