/**
 * Extractor stub generator. Default kind for `sm plugins create`: emits a
 * keyword-counter extractor with one setting (`string-list`) and one view
 * contribution (slot `card.footer.left`), both pulled from the catalog
 * defaults so a catalog change can never leave a stale literal behind.
 */

import { DEFAULT_INPUT_TYPE, DEFAULT_SLOT } from './defaults.js';
import type { IKindGenerator, IScaffoldFile } from './types.js';

function stub(extId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the extract() body.
 *
 * Loader contract: the plugin loader resolves the extension via the
 * MODULE'S DEFAULT EXPORT (\`export default { ... }\`). It must be an
 * object literal; renaming or splitting into a named export surfaces as
 * a \`load-error\`.
 *
 * Folder convention: this file lives at
 * \`extractors/${extId}/index.js\`. The folder layout is the source of
 * truth (structure-as-truth): the loader derives \`kind\`
 * (\`extractor\`) from the parent folder and the id (\`${extId}\`) from
 * the leaf folder, and injects \`pluginId\` from the plugin, so none of
 * them are declared here. Re-declaring \`kind\` / \`id\` is rejected as
 * \`invalid-manifest\`.
 *
 * Declared view contributions (\`ui\`):
 *   - 'count' → slot \`${DEFAULT_SLOT}\` (renders as a chip in the node
 *     card footer)
 *
 * Declared settings (\`settings\`):
 *   - 'keywords' (${DEFAULT_INPUT_TYPE}) → exposed as ctx.settings.keywords
 *
 * View contributions: declare each one as a const, list it in \`ui\` by
 * shorthand, and pass that SAME const (by reference, not a string id) to
 * \`ctx.emitContribution\`. The kernel recovers the contribution from the
 * object identity. (Write the plugin in TypeScript and add
 * \`satisfies IViewContribution\` from '@skill-map/cli' to get a typed payload.)
 *
 * See: spec/plugin-author-guide.md §View contributions
 *      spec/view-slots.md
 */
const count = {
  slot: '${DEFAULT_SLOT}',
  icon: '🔍',
  label: 'kw',
  emitWhenEmpty: false,
};

export default {
  version: '0.1.0',
  description: 'Counts configured keywords per node.',
  scope: 'body',

  settings: {
    keywords: {
      type: '${DEFAULT_INPUT_TYPE}',
      label: 'Keywords to track',
      description: 'Words counted across each scanned node body.',
      default: ['TODO', 'FIXME'],
      min: 1,
    },
  },

  ui: { count },

  extract(ctx) {
    const keywords = (ctx.settings && ctx.settings.keywords) || ['TODO', 'FIXME'];
    let total = 0;
    for (const kw of keywords) {
      const re = new RegExp('\\\\b' + kw.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&') + '\\\\b', 'gi');
      total += (ctx.body.match(re) || []).length;
    }
    if (total > 0) {
      ctx.emitContribution(count, { value: total });
    }
  },
};
`;
}

export const extractorGenerator: IKindGenerator = {
  folder: 'extractors',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-extractor`;
    return [{ relPath: `extractors/${ext}/index.js`, contents: stub(ext) }];
  },
};
