/**
 * Formatter stub generator. Emits a formatter that turns the persisted
 * scan into a string for `sm graph --format <id>`. The format id is
 * derived from the folder, so the stub declares `contentType` but NOT
 * `formatId` (a re-declared `formatId` is rejected as `invalid-manifest`).
 */

import type { IKindGenerator, IScaffoldFile } from './types.js';

function stub(extId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the format() body.
 *
 * Loader contract: default export object literal; \`kind\` (formatter) and
 * id (\`${extId}\`) come from the folder layout (structure-as-truth). The
 * format id used by \`sm graph --format ${extId}\` is the folder name; do
 * NOT declare \`formatId\` (derived, re-declaring it is invalid-manifest).
 *
 * \`format(ctx)\` returns a string. \`ctx.scanResult\` is the full
 * persisted scan (the canonical input); \`ctx.nodes\` / \`ctx.links\` /
 * \`ctx.issues\` are the same data split out for convenience. Output has
 * no trailing newline guarantee; the calling verb adds one if it needs.
 *
 * See: spec/plugin-author-guide.md, spec/schemas/extensions/formatter.schema.json
 */
export default {
  version: '0.1.0',
  description: 'Renders the scan as a one-line node/link/issue tally.',
  contentType: 'text/plain',

  format(ctx) {
    const nodes = ctx.nodes || [];
    const links = ctx.links || [];
    const issues = ctx.issues || [];
    return \`nodes=\${nodes.length} links=\${links.length} issues=\${issues.length}\`;
  },
};
`;
}

export const formatterGenerator: IKindGenerator = {
  folder: 'formatters',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-formatter`;
    return [{ relPath: `formatters/${ext}/index.js`, contents: stub(ext) }];
  },
};
