/**
 * Hook stub generator. Emits a deterministic hook subscribed to `boot`.
 * Hooks react to kernel lifecycle events; they cannot block or alter the
 * pipeline. `triggers` is required and must be from the curated event set.
 */

import type { IKindGenerator, IScaffoldFile } from './types.js';

function stub(extId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the on() body.
 *
 * Loader contract: default export object literal; \`kind\` (hook) and id
 * (\`${extId}\`) come from the folder layout (structure-as-truth). Hooks
 * are deterministic-only: to run LLM work, enqueue a probabilistic Action
 * via \`ctx.queue('<plugin>/<action>', payload)\` instead.
 *
 * \`triggers\` is the curated set this hook subscribes to (one of: boot,
 * scan.started, scan.completed, extractor.completed, analyzer.completed,
 * action.completed, job.spawning, job.completed, job.failed, shutdown).
 * \`on(ctx)\` reads the event off \`ctx.event\` (\`ctx.event.data\` is the
 * payload); the dispatcher catches errors so a throw never breaks the verb.
 *
 * See: spec/plugin-author-guide.md, spec/schemas/extensions/hook.schema.json
 */
export default {
  triggers: ['boot'],

  async on(ctx) {
    const data = (ctx.event && ctx.event.data) || {};
    // No-op demo. A real hook reacts here, e.g. inspect \`data\`, write a
    // log line, or enqueue an action with ctx.queue(...).
    void data;
  },
};
`;
}

export const hookGenerator: IKindGenerator = {
  folder: 'hooks',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-hook`;
    return [{ relPath: `hooks/${ext}/index.js`, contents: stub(ext) }];
  },
};
