/**
 * Scaffolder orchestrator for `sm plugins create`. Owns the kind →
 * generator registry, the shared `plugin.json` manifest builder, and
 * `generateScaffold`, which assembles the full file list (manifest +
 * extension stub(s) + README) for a chosen kind.
 *
 * The `Record<ExtensionKind, IKindGenerator>` is exhaustive by typing:
 * adding a kind to `EXTENSION_KINDS` fails the build here until a
 * generator is wired, so a new kind can never silently lack a scaffold.
 */

import type { ExtensionKind } from '../../../../kernel/registry.js';
import { actionGenerator } from './action.js';
import { analyzerGenerator } from './analyzer.js';
import { extractorGenerator } from './extractor.js';
import { formatterGenerator } from './formatter.js';
import { hookGenerator } from './hook.js';
import { providerGenerator } from './provider.js';
import { scaffolderReadme } from './readme.js';
import type { IScaffoldFile, IKindGenerator } from './types.js';

const GENERATORS: Record<ExtensionKind, IKindGenerator> = {
  provider: providerGenerator,
  extractor: extractorGenerator,
  analyzer: analyzerGenerator,
  action: actionGenerator,
  formatter: formatterGenerator,
  hook: hookGenerator,
};

/**
 * Plugin manifest only. `id` is derived from the folder name and settings
 * live per-extension (in the extension's index.js) since the
 * structure-as-truth refactor; both are rejected at the root by
 * `plugins-registry.schema.json#/$defs/PluginManifest`.
 */
export function pluginManifest(specVersion: string): Record<string, unknown> {
  return {
    version: '0.1.0',
    specCompat: `^${specVersion}`,
    catalogCompat: '^1.0.0',
    description: 'Generated by `sm plugins create`. Edit to taste.',
  };
}

/**
 * Assemble every file a freshly scaffolded plugin needs for `kind`:
 * the plugin manifest, the extension stub(s), and the README. Paths are
 * relative to the plugin root.
 */
export function generateScaffold(
  kind: ExtensionKind,
  pluginId: string,
  specVersion: string,
): IScaffoldFile[] {
  const extFiles = GENERATORS[kind].files(pluginId);
  const main = extFiles[0];
  if (!main) {
    throw new Error(`scaffold generator for kind '${kind}' returned no files`);
  }
  return [
    {
      relPath: 'plugin.json',
      contents: JSON.stringify(pluginManifest(specVersion), null, 2) + '\n',
    },
    ...extFiles,
    { relPath: 'README.md', contents: scaffolderReadme(pluginId, kind, main.relPath) },
  ];
}
