/**
 * Provider stub generator (skeleton). A Provider declares a platform's
 * identity and the node kinds it emits. The kinds catalog is discovered
 * from `<plugin>/kinds/<kindName>/{schema.json,kind.json}` on disk (the
 * manifest never carries a `kinds` map). This skeleton ships ONLY the
 * provider `index.js` with `presentation` + a `classify()` that returns
 * null, plus a TODO walking the author through adding a real kind.
 */

import type { IKindGenerator, IScaffoldFile } from './types.js';

function titleCase(id: string): string {
  return id
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

function stub(pluginId: string, extId: string): string {
  const label = titleCase(pluginId);
  return `/**
 * Generated by \`sm plugins create\`. Skeleton provider: edit classify()
 * and add a kind under \`kinds/\` (see the TODO below).
 *
 * Loader contract: default export object literal; \`kind\` (provider) and
 * id (\`${extId}\`) come from the folder layout (structure-as-truth). Do
 * NOT declare a \`kinds\` map here, it is rejected as invalid-manifest;
 * kinds are discovered from \`kinds/<kindName>/\` folders at the PLUGIN
 * root.
 *
 * \`presentation\` (label + hex color) is required: the UI reads it for
 * the lens dropdown, the topbar chip, and the per-node provider chip.
 * \`read\` configures file discovery (defaults to \`.md\` +
 * frontmatter-yaml when omitted). \`classify(path, frontmatter)\` returns
 * the node kind for files this provider owns, or null to let the file
 * fall through to the markdown fallback.
 *
 * TODO: this skeleton classifies nothing (returns null). To emit nodes:
 *   1. Pick a kind name, e.g. 'note'.
 *   2. Create \`kinds/note/schema.json\` (frontmatter JSON Schema,
 *      allOf + $ref to frontmatter/base.schema.json).
 *   3. Create \`kinds/note/kind.json\` ({ "ui": { "label": "...",
 *      "color": "#......" } }).
 *   4. Return 'note' from classify() for the files you own.
 *
 * See: spec/plugin-author-guide.md, spec/schemas/extensions/provider.schema.json
 */
export default {
  version: '0.1.0',
  description: 'Skeleton provider; classify() returns null until a kind is added.',

  presentation: {
    label: '${label}',
    color: '#6b7280',
  },

  read: { extensions: ['.md'], parser: 'frontmatter-yaml' },

  classify(path, frontmatter) {
    // TODO: return a kind name (see header) for files this provider owns.
    void path;
    void frontmatter;
    return null;
  },
};
`;
}

export const providerGenerator: IKindGenerator = {
  folder: 'providers',
  files(pluginId: string): IScaffoldFile[] {
    const ext = `${pluginId}-provider`;
    return [{ relPath: `providers/${ext}/index.js`, contents: stub(pluginId, ext) }];
  },
};
