/**
 * README generator, shared across kinds. Points the author at the stub
 * they just scaffolded and the verbs / spec docs they need next.
 */

import type { ExtensionKind } from '../../../../kernel/registry.js';

export function scaffolderReadme(
  pluginId: string,
  kind: ExtensionKind,
  mainFileRel: string,
): string {
  return `# ${pluginId}

Generated by \`sm plugins create ${kind} ${pluginId}\`. Edit \`${mainFileRel}\` to taste.

## Verbs

- \`sm plugins list ${pluginId}\`: manifest + extensions + load status
- \`sm plugins doctor\`: full plugin diagnostic
- \`sm scan\`: re-emit contributions / re-run analysis

## Resources

- \`spec/plugin-author-guide.md\`: authoring guide for every kind
- \`spec/view-slots.md\`: the closed catalog of view slots
- \`spec/input-types.md\`: the closed catalog of setting input-types
- \`sm plugins slots list\`: browse the slot / input-type catalog from the CLI
`;
}
