/**
 * Ignore file for a folder skill-map MATERIALISES outside the scope
 * directory (`spec/cli-contract.md` §Scope ignore file → Materialised
 * skill folders): `<skillDir>/sm-process-jobs/` (`sm agent install`) and
 * `<skillDir>/sm-tutorial/` (`sm tutorial`).
 *
 * Those folders are a verbatim copy of what the CLI ships, compared
 * byte-for-byte to decide staleness and rewritten on demand. That makes
 * them generated artifacts, and the same reasoning that put the ignore
 * rules INSIDE `.skill-map/` (`core/scope-gitignore.ts`) applies here:
 * the rule travels with the directory it describes, and skill-map never
 * edits the project-root `.gitignore`, a file it does not own.
 *
 * The body is a single `*`, which also hides the ignore file itself, so
 * the whole folder disappears from git rather than leaving a one-line
 * husk behind.
 *
 * Three bounds, all deliberate:
 *
 *   - **FRESH ONLY.** The callers invoke this when they CREATE the
 *     folder, never on a refresh. Re-materialising is the common path,
 *     and an operator who deleted the file (or added negations) did so
 *     precisely to commit the folder.
 *   - **NEVER OVERWRITES.** An existing `.gitignore` is left alone even
 *     on a fresh install, it can only be the operator's.
 *   - **TOTAL.** Every filesystem error resolves to `false`. The ignore
 *     file is a convenience; the skill is the deliverable, and a
 *     read-only parent must not fail the install that triggered it.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Body written into a freshly materialised folder. */
const IGNORE_BODY = [
  '# Managed by skill-map: this folder is generated by the CLI and',
  '# re-materialised on demand, so it does not belong in the repo.',
  '# Delete this file to commit it anyway.',
  '*',
];

/**
 * Write `<folder>/.gitignore` unless it already exists. Returns `true`
 * when the file was created, `false` when it was already there or the
 * write failed (indistinguishable to callers on purpose: neither is
 * actionable).
 */
export function ensureGeneratedFolderGitignore(folder: string): boolean {
  const path = join(folder, '.gitignore');
  try {
    if (existsSync(path)) return false;
    writeFileSync(path, `${IGNORE_BODY.join('\n')}\n`, 'utf8');
    return true;
  } catch {
    return false;
  }
}
