// AUTO-GENERATED by scripts/generate-built-ins.js. Do not edit by hand.
// Regenerate with `pnpm --filter @skill-map/cli build-built-ins`.
// Source of truth: each bundle's plugin.json + filesystem layout under
// src/plugins/<bundle>/<kind>s/<name>/index.ts.

import type {
  IAction,
  IProvider,
  IExtractor,
  IFormatter,
  IHook,
  IAnalyzer,
} from '../kernel/extensions/index.js';
import type { IExtension } from '../kernel/registry.js';
import { bucketByKind } from '../kernel/util/bucket-by-kind.js';

import { claudeProvider as _claudeProvider } from './claude/providers/claude/index.js';
import { atDirectiveExtractor as _atDirectiveExtractor } from './claude/extractors/at-directive/index.js';
import { slashCommandExtractor as _slashCommandExtractor } from './claude/extractors/slash-command/index.js';
import { antigravityProvider as _antigravityProvider } from './antigravity/providers/antigravity/index.js';
import { openaiProvider as _openaiProvider } from './openai/providers/openai/index.js';
import { agentSkillsProvider as _agentSkillsProvider } from './agent-skills/providers/agent-skills/index.js';
import { coreMarkdownProvider as _coreMarkdownProvider } from './core/providers/core-markdown/index.js';
import { annotationsExtractor as _annotationsExtractor } from './core/extractors/annotations/index.js';
import { externalUrlCounterExtractor as _externalUrlCounterExtractor } from './core/extractors/external-url-counter/index.js';
import { markdownLinkExtractor as _markdownLinkExtractor } from './core/extractors/markdown-link/index.js';
import { mcpToolsExtractor as _mcpToolsExtractor } from './core/extractors/mcp-tools/index.js';
import { toolsCounterExtractor as _toolsCounterExtractor } from './core/extractors/tools-counter/index.js';
import { annotationFieldUnknownAnalyzer as _annotationFieldUnknownAnalyzer } from './core/analyzers/annotation-field-unknown/index.js';
import { annotationOrphanAnalyzer as _annotationOrphanAnalyzer } from './core/analyzers/annotation-orphan/index.js';
import { annotationStaleAnalyzer as _annotationStaleAnalyzer } from './core/analyzers/annotation-stale/index.js';
import { contributionOrphanAnalyzer as _contributionOrphanAnalyzer } from './core/analyzers/contribution-orphan/index.js';
import { issueCounterAnalyzer as _issueCounterAnalyzer } from './core/analyzers/issue-counter/index.js';
import { jobFileOrphanAnalyzer as _jobFileOrphanAnalyzer } from './core/analyzers/job-file-orphan/index.js';
import { linkConflictAnalyzer as _linkConflictAnalyzer } from './core/analyzers/link-conflict/index.js';
import { linkCounterAnalyzer as _linkCounterAnalyzer } from './core/analyzers/link-counter/index.js';
import { linkSelfLoopAnalyzer as _linkSelfLoopAnalyzer } from './core/analyzers/link-self-loop/index.js';
import { nameReservedAnalyzer as _nameReservedAnalyzer } from './core/analyzers/name-reserved/index.js';
import { nodeStabilityAnalyzer as _nodeStabilityAnalyzer } from './core/analyzers/node-stability/index.js';
import { nodeSupersededAnalyzer as _nodeSupersededAnalyzer } from './core/analyzers/node-superseded/index.js';
import { referenceBrokenAnalyzer as _referenceBrokenAnalyzer } from './core/analyzers/reference-broken/index.js';
import { referenceRedundantAnalyzer as _referenceRedundantAnalyzer } from './core/analyzers/reference-redundant/index.js';
import { schemaViolationAnalyzer as _schemaViolationAnalyzer } from './core/analyzers/schema-violation/index.js';
import { signalCollisionAnalyzer as _signalCollisionAnalyzer } from './core/analyzers/signal-collision/index.js';
import { triggerCollisionAnalyzer as _triggerCollisionAnalyzer } from './core/analyzers/trigger-collision/index.js';
import { asciiFormatter as _asciiFormatter } from './core/formatters/ascii/index.js';
import { jsonFormatter as _jsonFormatter } from './core/formatters/json/index.js';
import { nodeBumpAction as _nodeBumpAction } from './core/actions/node-bump/index.js';
import { nodeSupersedeAction as _nodeSupersedeAction } from './core/actions/node-supersede/index.js';
import { updateCheckHook as _updateCheckHook } from './core/hooks/update-check/index.js';

const claudeProvider = { ..._claudeProvider, pluginId: 'claude', version: '0.43.0' };
const atDirectiveExtractor = { ..._atDirectiveExtractor, pluginId: 'claude', version: '0.43.0' };
const slashCommandExtractor = { ..._slashCommandExtractor, pluginId: 'claude', version: '0.43.0' };
const antigravityProvider = { ..._antigravityProvider, pluginId: 'antigravity', version: '0.43.0' };
const openaiProvider = { ..._openaiProvider, pluginId: 'openai', version: '0.43.0' };
const agentSkillsProvider = { ..._agentSkillsProvider, pluginId: 'agent-skills', version: '0.43.0' };
const coreMarkdownProvider = { ..._coreMarkdownProvider, pluginId: 'core', version: '0.43.0' };
const annotationsExtractor = { ..._annotationsExtractor, pluginId: 'core', version: '0.43.0' };
const externalUrlCounterExtractor = { ..._externalUrlCounterExtractor, pluginId: 'core', version: '0.43.0' };
const markdownLinkExtractor = { ..._markdownLinkExtractor, pluginId: 'core', version: '0.43.0' };
const mcpToolsExtractor = { ..._mcpToolsExtractor, pluginId: 'core', version: '0.43.0' };
const toolsCounterExtractor = { ..._toolsCounterExtractor, pluginId: 'core', version: '0.43.0' };
const annotationFieldUnknownAnalyzer = { ..._annotationFieldUnknownAnalyzer, pluginId: 'core', version: '0.43.0' };
const annotationOrphanAnalyzer = { ..._annotationOrphanAnalyzer, pluginId: 'core', version: '0.43.0' };
const annotationStaleAnalyzer = { ..._annotationStaleAnalyzer, pluginId: 'core', version: '0.43.0' };
const contributionOrphanAnalyzer = { ..._contributionOrphanAnalyzer, pluginId: 'core', version: '0.43.0' };
const issueCounterAnalyzer = { ..._issueCounterAnalyzer, pluginId: 'core', version: '0.43.0' };
const jobFileOrphanAnalyzer = { ..._jobFileOrphanAnalyzer, pluginId: 'core', version: '0.43.0' };
const linkConflictAnalyzer = { ..._linkConflictAnalyzer, pluginId: 'core', version: '0.43.0' };
const linkCounterAnalyzer = { ..._linkCounterAnalyzer, pluginId: 'core', version: '0.43.0' };
const linkSelfLoopAnalyzer = { ..._linkSelfLoopAnalyzer, pluginId: 'core', version: '0.43.0' };
const nameReservedAnalyzer = { ..._nameReservedAnalyzer, pluginId: 'core', version: '0.43.0' };
const nodeStabilityAnalyzer = { ..._nodeStabilityAnalyzer, pluginId: 'core', version: '0.43.0' };
const nodeSupersededAnalyzer = { ..._nodeSupersededAnalyzer, pluginId: 'core', version: '0.43.0' };
const referenceBrokenAnalyzer = { ..._referenceBrokenAnalyzer, pluginId: 'core', version: '0.43.0' };
const referenceRedundantAnalyzer = { ..._referenceRedundantAnalyzer, pluginId: 'core', version: '0.43.0' };
const schemaViolationAnalyzer = { ..._schemaViolationAnalyzer, pluginId: 'core', version: '0.43.0' };
const signalCollisionAnalyzer = { ..._signalCollisionAnalyzer, pluginId: 'core', version: '0.43.0' };
const triggerCollisionAnalyzer = { ..._triggerCollisionAnalyzer, pluginId: 'core', version: '0.43.0' };
const asciiFormatter = { ..._asciiFormatter, pluginId: 'core', version: '0.43.0' };
const jsonFormatter = { ..._jsonFormatter, pluginId: 'core', version: '0.43.0' };
const nodeBumpAction = { ..._nodeBumpAction, pluginId: 'core', version: '0.43.0' };
const nodeSupersedeAction = { ..._nodeSupersedeAction, pluginId: 'core', version: '0.43.0' };
const updateCheckHook = { ..._updateCheckHook, pluginId: 'core', version: '0.43.0' };

export interface IBuiltIns {
  providers: IProvider[];
  extractors: IExtractor[];
  analyzers: IAnalyzer[];
  formatters: IFormatter[];
  actions: IAction[];
  hooks: IHook[];
}

export type TBuiltInExtension = IProvider | IExtractor | IAnalyzer | IAction | IFormatter | IHook;

export interface IBuiltInBundle {
  id: string;
  description: string;
  extensions: TBuiltInExtension[];
}

export const builtInBundles: IBuiltInBundle[] = [
  {
    id: 'claude',
    description: 'Claude Code platform integration. Classifies files under `.claude/{agents,commands,skills}` and detects Claude-flavored slash commands and at-directives in their bodies.',
    extensions: [
      claudeProvider,
      atDirectiveExtractor,
      slashCommandExtractor,
    ],
  },
  {
    id: 'antigravity',
    description: 'Google Antigravity CLI platform integration (replaces the retired Gemini CLI). Antigravity adopted the open-standard `.agents/` layout, so skills are classified by the neutral `agent-skills` provider; this plugin contributes the Antigravity runtime identity and a seed list of reserved built-in names.',
    extensions: [
      antigravityProvider,
    ],
  },
  {
    id: 'openai',
    description: 'OpenAI Codex CLI platform integration. Classifies TOML sub-agent definitions under `.codex/agents/*.toml`.',
    extensions: [
      openaiProvider,
    ],
  },
  {
    id: 'agent-skills',
    description: 'Open-standard Agent Skills layout. Classifies skills under the vendor-neutral path `.agents/skills/<name>/SKILL.md` (adopted by Anthropic, OpenAI, Google). See agentskills.io.',
    extensions: [
      agentSkillsProvider,
    ],
  },
  {
    id: 'core',
    description: 'Core extensions shared across providers: parsers, extractors, analyzers, actions, hooks, formatters, and the universal `.md` fallback provider.',
    extensions: [
      coreMarkdownProvider,
      annotationsExtractor,
      externalUrlCounterExtractor,
      markdownLinkExtractor,
      mcpToolsExtractor,
      toolsCounterExtractor,
      annotationFieldUnknownAnalyzer,
      annotationOrphanAnalyzer,
      annotationStaleAnalyzer,
      contributionOrphanAnalyzer,
      issueCounterAnalyzer,
      jobFileOrphanAnalyzer,
      linkConflictAnalyzer,
      linkCounterAnalyzer,
      linkSelfLoopAnalyzer,
      nameReservedAnalyzer,
      nodeStabilityAnalyzer,
      nodeSupersededAnalyzer,
      referenceBrokenAnalyzer,
      referenceRedundantAnalyzer,
      schemaViolationAnalyzer,
      signalCollisionAnalyzer,
      triggerCollisionAnalyzer,
      asciiFormatter,
      jsonFormatter,
      nodeBumpAction,
      nodeSupersedeAction,
      updateCheckHook,
    ],
  },
];

export function builtIns(): IBuiltIns {
  const out: IBuiltIns = {
    providers: [],
    extractors: [],
    analyzers: [],
    formatters: [],
    actions: [],
    hooks: [],
  };
  for (const bundle of builtInBundles) {
    for (const ext of bundle.extensions) {
      bucketBuiltIn(ext, out);
    }
  }
  return out;
}

export function listBuiltIns(): IExtension[] {
  const out: IExtension[] = [];
  for (const bundle of builtInBundles) {
    for (const x of bundle.extensions) {
      out.push(toExtensionRow(x));
    }
  }
  return out;
}

function bucketBuiltIn(ext: TBuiltInExtension, out: IBuiltIns): void {
  bucketByKind(ext.kind, ext, {
    provider: out.providers,
    extractor: out.extractors,
    analyzer: out.analyzers,
    formatter: out.formatters,
    action: out.actions,
    hook: out.hooks,
  });
}

function toExtensionRow(x: TBuiltInExtension): IExtension {
  const row: IExtension = {
    id: x.id,
    pluginId: x.pluginId,
    kind: x.kind,
    version: x.version,
    description: x.description ?? '',
  };
  return row;
}
