// AUTO-GENERATED by scripts/generate-built-ins.js. Do not edit by hand.
// Regenerate with `pnpm --filter @skill-map/cli build-built-ins`.
// Source of truth: each bundle's plugin.json + filesystem layout under
// src/plugins/<bundle>/<kind>s/<name>/index.ts.

import type {
  IAction,
  IProvider,
  IExtractor,
  IFormatter,
  IHook,
  IAnalyzer,
} from '../kernel/extensions/index.js';
import type { Extension } from '../kernel/registry.js';
import type { TGranularity } from '../kernel/types/plugin.js';
import { bucketByKind } from '../kernel/util/bucket-by-kind.js';

import { claudeProvider as _claudeProvider } from './claude/providers/claude/index.js';
import { geminiProvider as _geminiProvider } from './gemini/providers/gemini/index.js';
import { agentSkillsProvider as _agentSkillsProvider } from './agent-skills/providers/agent-skills/index.js';
import { coreMarkdownProvider as _coreMarkdownProvider } from './core/providers/core-markdown/index.js';
import { annotationsExtractor as _annotationsExtractor } from './core/extractors/annotations/index.js';
import { atDirectiveExtractor as _atDirectiveExtractor } from './core/extractors/at-directive/index.js';
import { externalUrlCounterExtractor as _externalUrlCounterExtractor } from './core/extractors/external-url-counter/index.js';
import { markdownLinkExtractor as _markdownLinkExtractor } from './core/extractors/markdown-link/index.js';
import { slashExtractor as _slashExtractor } from './core/extractors/slash/index.js';
import { toolsCountExtractor as _toolsCountExtractor } from './core/extractors/tools-count/index.js';
import { annotationOrphanAnalyzer as _annotationOrphanAnalyzer } from './core/analyzers/annotation-orphan/index.js';
import { annotationStaleAnalyzer as _annotationStaleAnalyzer } from './core/analyzers/annotation-stale/index.js';
import { brokenRefAnalyzer as _brokenRefAnalyzer } from './core/analyzers/broken-ref/index.js';
import { contributionOrphanAnalyzer as _contributionOrphanAnalyzer } from './core/analyzers/contribution-orphan/index.js';
import { jobOrphanFileAnalyzer as _jobOrphanFileAnalyzer } from './core/analyzers/job-orphan-file/index.js';
import { linkConflictAnalyzer as _linkConflictAnalyzer } from './core/analyzers/link-conflict/index.js';
import { linkCountsAnalyzer as _linkCountsAnalyzer } from './core/analyzers/link-counts/index.js';
import { stabilityAnalyzer as _stabilityAnalyzer } from './core/analyzers/stability/index.js';
import { supersededAnalyzer as _supersededAnalyzer } from './core/analyzers/superseded/index.js';
import { triggerCollisionAnalyzer as _triggerCollisionAnalyzer } from './core/analyzers/trigger-collision/index.js';
import { unknownFieldAnalyzer as _unknownFieldAnalyzer } from './core/analyzers/unknown-field/index.js';
import { validateAllAnalyzer as _validateAllAnalyzer } from './core/analyzers/validate-all/index.js';
import { asciiFormatter as _asciiFormatter } from './core/formatters/ascii/index.js';
import { jsonFormatter as _jsonFormatter } from './core/formatters/json/index.js';
import { bumpAction as _bumpAction } from './core/actions/bump/index.js';
import { markSupersededAction as _markSupersededAction } from './core/actions/mark-superseded/index.js';
import { updateCheckHook as _updateCheckHook } from './core/hooks/update-check/index.js';

const claudeProvider = { ..._claudeProvider, pluginId: 'claude' };
const geminiProvider = { ..._geminiProvider, pluginId: 'gemini' };
const agentSkillsProvider = { ..._agentSkillsProvider, pluginId: 'agent-skills' };
const coreMarkdownProvider = { ..._coreMarkdownProvider, pluginId: 'core' };
const annotationsExtractor = { ..._annotationsExtractor, pluginId: 'core' };
const atDirectiveExtractor = { ..._atDirectiveExtractor, pluginId: 'core' };
const externalUrlCounterExtractor = { ..._externalUrlCounterExtractor, pluginId: 'core' };
const markdownLinkExtractor = { ..._markdownLinkExtractor, pluginId: 'core' };
const slashExtractor = { ..._slashExtractor, pluginId: 'core' };
const toolsCountExtractor = { ..._toolsCountExtractor, pluginId: 'core' };
const annotationOrphanAnalyzer = { ..._annotationOrphanAnalyzer, pluginId: 'core' };
const annotationStaleAnalyzer = { ..._annotationStaleAnalyzer, pluginId: 'core' };
const brokenRefAnalyzer = { ..._brokenRefAnalyzer, pluginId: 'core' };
const contributionOrphanAnalyzer = { ..._contributionOrphanAnalyzer, pluginId: 'core' };
const jobOrphanFileAnalyzer = { ..._jobOrphanFileAnalyzer, pluginId: 'core' };
const linkConflictAnalyzer = { ..._linkConflictAnalyzer, pluginId: 'core' };
const linkCountsAnalyzer = { ..._linkCountsAnalyzer, pluginId: 'core' };
const stabilityAnalyzer = { ..._stabilityAnalyzer, pluginId: 'core' };
const supersededAnalyzer = { ..._supersededAnalyzer, pluginId: 'core' };
const triggerCollisionAnalyzer = { ..._triggerCollisionAnalyzer, pluginId: 'core' };
const unknownFieldAnalyzer = { ..._unknownFieldAnalyzer, pluginId: 'core' };
const validateAllAnalyzer = { ..._validateAllAnalyzer, pluginId: 'core' };
const asciiFormatter = { ..._asciiFormatter, pluginId: 'core' };
const jsonFormatter = { ..._jsonFormatter, pluginId: 'core' };
const bumpAction = { ..._bumpAction, pluginId: 'core' };
const markSupersededAction = { ..._markSupersededAction, pluginId: 'core' };
const updateCheckHook = { ..._updateCheckHook, pluginId: 'core' };

export interface IBuiltIns {
  providers: IProvider[];
  extractors: IExtractor[];
  analyzers: IAnalyzer[];
  formatters: IFormatter[];
  actions: IAction[];
  hooks: IHook[];
}

export type TBuiltInExtension = IProvider | IExtractor | IAnalyzer | IAction | IFormatter | IHook;

export interface IBuiltInBundle {
  id: string;
  granularity: TGranularity;
  description: string;
  extensions: TBuiltInExtension[];
}

export const builtInBundles: IBuiltInBundle[] = [
  {
    id: 'claude',
    granularity: 'bundle',
    description: 'Claude Code platform integration. Classifies files under `.claude/{agents,commands,skills}` and parses Claude-flavored frontmatter.',
    extensions: [
      claudeProvider,
    ],
  },
  {
    id: 'gemini',
    granularity: 'bundle',
    description: 'Gemini CLI platform integration. Classifies files under `.gemini/{agents,skills}` and parses Gemini-flavored frontmatter.',
    extensions: [
      geminiProvider,
    ],
  },
  {
    id: 'agent-skills',
    granularity: 'bundle',
    description: 'Agent Skills open standard. Vendor-neutral path `.agents/skills/<name>/SKILL.md` (Anthropic, OpenAI, Google). See agentskills.io.',
    extensions: [
      agentSkillsProvider,
    ],
  },
  {
    id: 'core',
    granularity: 'extension',
    description: 'Core extensions shared across providers: extractors, analyzers, formatters, the bump action, and the universal `.md` fallback Provider.',
    extensions: [
      coreMarkdownProvider,
      annotationsExtractor,
      atDirectiveExtractor,
      externalUrlCounterExtractor,
      markdownLinkExtractor,
      slashExtractor,
      toolsCountExtractor,
      annotationOrphanAnalyzer,
      annotationStaleAnalyzer,
      brokenRefAnalyzer,
      contributionOrphanAnalyzer,
      jobOrphanFileAnalyzer,
      linkConflictAnalyzer,
      linkCountsAnalyzer,
      stabilityAnalyzer,
      supersededAnalyzer,
      triggerCollisionAnalyzer,
      unknownFieldAnalyzer,
      validateAllAnalyzer,
      asciiFormatter,
      jsonFormatter,
      bumpAction,
      markSupersededAction,
      updateCheckHook,
    ],
  },
];

export function builtIns(): IBuiltIns {
  const out: IBuiltIns = {
    providers: [],
    extractors: [],
    analyzers: [],
    formatters: [],
    actions: [],
    hooks: [],
  };
  for (const bundle of builtInBundles) {
    for (const ext of bundle.extensions) {
      bucketBuiltIn(ext, out);
    }
  }
  return out;
}

export function listBuiltIns(): Extension[] {
  const out: Extension[] = [];
  for (const bundle of builtInBundles) {
    for (const x of bundle.extensions) {
      out.push(toExtensionRow(x));
    }
  }
  return out;
}

function bucketBuiltIn(ext: TBuiltInExtension, out: IBuiltIns): void {
  bucketByKind(ext.kind, ext, {
    provider: out.providers,
    extractor: out.extractors,
    analyzer: out.analyzers,
    formatter: out.formatters,
    action: out.actions,
    hook: out.hooks,
  });
}

function toExtensionRow(x: TBuiltInExtension): Extension {
  const row: Extension = {
    id: x.id,
    pluginId: x.pluginId,
    kind: x.kind,
    version: x.version,
    description: x.description ?? '',
  };
  return row;
}
