/**
 * Single source of truth for the built-in plugin ids that every
 * built-in extension stamps into its `pluginId` field. The literals
 * (`'core'`, `'claude'`, `'codex'`, etc.) used to be hardcoded
 * across ~30 extension files; routing them through this catalog
 * keeps the IDs in one place so a rename is a one-line diff instead
 * of a multi-file sweep.
 *
 * The runtime strings MUST match what `src/plugins/built-ins.ts`
 * (auto-generated by `scripts/generate-built-ins.js`) stamps into
 * the spread overrides: changing a value here without the matching
 * generator update would split the runtime identity in half.
 */

export const CORE_PLUGIN_ID = 'core';
export const CLAUDE_PLUGIN_ID = 'claude';
export const CODEX_PLUGIN_ID = 'codex';
export const ANTIGRAVITY_PLUGIN_ID = 'antigravity';
export const AGENT_SKILLS_PLUGIN_ID = 'agent-skills';
export const OPENCODE_PLUGIN_ID = 'opencode';
export const GITHUB_PLUGIN_ID = 'github';
export const TEST_PLUGIN_PLUGIN_ID = 'test-plugin';
