/**
 * Built-in plugin ordering for **presentation** surfaces (`sm plugins
 * list / show / doctor`, BFF `GET /api/plugins`, Settings → Plugins).
 *
 * Why this lives outside `built-ins.ts`: that file is auto-generated by
 * `scripts/generate-built-ins.js` and a hand-edit there gets wiped on
 * every regeneration. The runtime iteration order, also driven by the
 * generated array, keeps `core` LAST so `core/markdown` stays the
 * terminal universal-fallback provider (per `spec/architecture.md`
 * §"core/markdown is the universal fallback for unclaimed `.md`
 * files"). Presentation has the inverse intuition, the things the user
 * touches most should appear first, so we sort the runtime array at
 * the call sites that show plugins to humans.
 *
 * Keep `BUILT_IN_PLUGIN_PRESENTATION_ORDER` aligned with the UI's
 * `PINNED_PLUGIN_ORDER` in
 * `ui/src/app/components/settings-modal/settings-plugins.utils.ts`,
 * the two arrays must stay in lockstep so the CLI listing and the
 * SPA's pinned-top rows match.
 */

export const BUILT_IN_PLUGIN_PRESENTATION_ORDER: readonly string[] = [
  'core',
  'claude',
  'antigravity',
  'openai',
  'agent-skills',
];

/**
 * Stable sort by presentation order. Ids not in
 * `BUILT_IN_PLUGIN_PRESENTATION_ORDER` land at the end, alphabetically,
 * so a future built-in (or any custom array a caller passes) slots in
 * predictably without needing this file to know about it.
 */
export function sortPluginsForPresentation<T extends { id: string }>(
  plugins: readonly T[],
): T[] {
  const orderIndex = (id: string): number => {
    const idx = BUILT_IN_PLUGIN_PRESENTATION_ORDER.indexOf(id);
    return idx >= 0 ? idx : BUILT_IN_PLUGIN_PRESENTATION_ORDER.length;
  };
  return [...plugins].sort((a, b) => {
    const ai = orderIndex(a.id);
    const bi = orderIndex(b.id);
    if (ai !== bi) return ai - bi;
    return a.id.localeCompare(b.id);
  });
}
