/**
 * `sm hooks install pre-commit-bump [--dry-run]`
 *
 * Step 9.6.4 (Decision A1 + A6 + A7). Installs (or chains into) a git
 * pre-commit hook that runs `sm bump --pending --staged` so any
 * staged drift in `.sm` sidecars auto-bumps before the commit lands.
 *
 * Behaviour:
 *
 *   - When `<repo>/.git/hooks/pre-commit` does not exist → write the
 *     full hook with the skill-map block.
 *   - When the file exists and already carries the skill-map marker →
 *     no-op (idempotent re-install).
 *   - When the file exists without the marker → append the skill-map
 *     block to the end (preserving the user's existing hook).
 *
 * `--dry-run` prints the planned content + target path with
 * `--- target: <path> ---` markers and writes nothing.
 *
 * Exit codes (Decision A6):
 *   0  ok / already installed
 *   2  install failure (write error, etc.)
 *   5  not inside a git repo (no .git/ at or above cwd)
 */

import { chmod, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { Command, Option } from 'clipanion';

import { formatErrorMessage } from '../../kernel/util/format-error.js';
import { tx } from '../../kernel/util/tx.js';
import { HOOKS_TEXTS } from '../i18n/hooks.texts.js';
import { ExitCode } from '../util/exit-codes.js';
import { pathExists } from '../util/fs.js';
import { defaultRuntimeContext } from '../../core/runtime/runtime-context.js';
import { SmCommand } from '../util/sm-command.js';

/**
 * Marker that lets a re-install detect its own block. Embedded in the
 * hook body as a comment.
 */
const SKILL_MAP_MARKER = '# >>> skill-map pre-commit-bump >>>';
const SKILL_MAP_MARKER_END = '# <<< skill-map pre-commit-bump <<<';

/**
 * Body of the skill-map block. Per Decision A7 the script uses
 * `#!/usr/bin/env bash`; the body runs `sm bump --pending --staged`
 * and aborts the commit on non-zero exit. When the hook already
 * exists with content, we append from `SKILL_MAP_MARKER` onward
 * (skipping the shebang line, the existing hook owns that).
 */
const HOOK_SHEBANG = '#!/usr/bin/env bash\n';
const SKILL_MAP_BLOCK = [
  SKILL_MAP_MARKER,
  '# Auto-bump staged sidecar drift before the commit lands.',
  '# Generated by `sm hooks install pre-commit-bump`. Do not edit;',
  '# re-run the install command to regenerate.',
  'set -e',
  'sm bump --pending --staged',
  SKILL_MAP_MARKER_END,
  '',
].join('\n');

const FRESH_HOOK_BODY = HOOK_SHEBANG + SKILL_MAP_BLOCK;

/**
 * `sm hooks install pre-commit-bump`. Single positional argument
 * (`pre-commit-bump`) so future hook flavours can land additively
 * without breaking the existing surface.
 */
export class HooksInstallCommand extends SmCommand {
  static override paths = [['hooks', 'install']];
  static override usage = Command.Usage({
    category: 'Actions',
    description:
      'Install a git pre-commit hook that auto-bumps staged sidecar drift.',
    details: `
      The only supported flavour today is \`pre-commit-bump\`, which
      runs \`sm bump --pending --staged\` from the repo's pre-commit
      hook so any drifted sidecar in the staged set gets a fresh
      version + audit stamp inside the same commit.

      Idempotent: re-running detects the skill-map marker and no-ops.
      When the repo already has a custom \`pre-commit\`, the verb
      appends the skill-map block to the existing file rather than
      replacing it.

      Requires a parent \`.git/\` (exit 5 otherwise). Writes nothing
      under \`--dry-run\`; instead prints the planned content with
      \`--- target: <path> ---\` markers.
    `,
    examples: [
      ['Install the hook', '$0 hooks install pre-commit-bump'],
      ['Preview what would be written', '$0 hooks install pre-commit-bump --dry-run'],
    ],
  });

  flavour = Option.String({ required: true });
  dryRun = Option.Boolean('-n,--dry-run', false);

  // The remaining cyclomatic count is from CLI ergonomics, flavour
  // guard, repo lookup, marker detection, dry-run / json / chained /
  // fresh branches each contributing a guard. Inner work already lives
  // in `computePlannedHookContent` and `findGitRepoRoot`.
  // eslint-disable-next-line complexity
  protected async run(): Promise<number> {
    const ansi = this.ansiFor('stdout');
    const okGlyph = ansi.green('✓');
    const errGlyph = ansi.red('✕');

    if (this.flavour !== 'pre-commit-bump') {
      this.printer!.error(
        tx(HOOKS_TEXTS.unknownFlavour, {
          glyph: errGlyph,
          flavour: this.flavour,
          hint: ansi.dim(HOOKS_TEXTS.unknownFlavourHint),
        }),
      );
      return ExitCode.Error;
    }

    const ctx = defaultRuntimeContext();
    const repoRoot = await findGitRepoRoot(ctx.cwd);
    if (repoRoot === null) {
      this.printer!.error(
        tx(HOOKS_TEXTS.notInGitRepo, {
          glyph: errGlyph,
          hint: ansi.dim(tx(HOOKS_TEXTS.notInGitRepoHint, { cwd: ctx.cwd })),
        }),
      );
      return ExitCode.NotFound;
    }
    const hooksDir = resolve(repoRoot, '.git', 'hooks');
    const hookPath = resolve(hooksDir, 'pre-commit');

    const existing = (await pathExists(hookPath)) ? await readFile(hookPath, 'utf8') : null;
    const planned = computePlannedHookContent(existing);

    if (planned.kind === 'already-installed') {
      this.printer!.info(tx(HOOKS_TEXTS.alreadyInstalled, { glyph: okGlyph, hookPath }));
      return ExitCode.Ok;
    }

    if (this.dryRun === true) {
      if (this.json) {
        this.printer!.data(
          JSON.stringify({
            hookPath,
            kind: planned.kind,
            content: planned.content,
            elapsedMs: this.elapsed!.ms(),
          }) + '\n',
        );
        return ExitCode.Ok;
      }
      this.printer!.info(tx(HOOKS_TEXTS.dryRunHeader, { hookPath }));
      this.printer!.data(tx(HOOKS_TEXTS.dryRunMarkerOpen, { hookPath }));
      this.printer!.data(planned.content);
      if (!planned.content.endsWith('\n')) this.printer!.data('\n');
      this.printer!.data(HOOKS_TEXTS.dryRunMarkerClose);
      return ExitCode.Ok;
    }

    try {
      // Ensure `.git/hooks/` exists, git ships it by default but
      // worktrees / shallow clones may not.
      if (!(await pathExists(hooksDir))) await mkdir(hooksDir, { recursive: true });
      await writeFile(hookPath, planned.content, { encoding: 'utf8' });
      await ensureExecutableBit(hookPath);
    } catch (err) {
      this.printer!.error(
        tx(HOOKS_TEXTS.installFailed, { glyph: errGlyph, message: formatErrorMessage(err) }),
      );
      return ExitCode.Error;
    }

    if (this.json) {
      this.printer!.data(
        JSON.stringify({
          hookPath,
          kind: planned.kind,
          elapsedMs: this.elapsed!.ms(),
        }) + '\n',
      );
      return ExitCode.Ok;
    }

    this.printer!.data(
      tx(
        planned.kind === 'chained' ? HOOKS_TEXTS.chainedExisting : HOOKS_TEXTS.installed,
        { glyph: okGlyph, hookPath },
      ),
    );
    return ExitCode.Ok;
  }
}

/**
 * Locate the nearest ancestor of `cwd` containing a `.git/` entry
 * (file or directory, worktrees use `.git` files). Returns the
 * directory that owns `.git/`, or `null` when no such ancestor
 * exists.
 */
async function findGitRepoRoot(cwd: string): Promise<string | null> {
  let current = cwd;
  while (true) {
    if (await pathExists(resolve(current, '.git'))) return current;
    const parent = dirname(current);
    if (parent === current) return null;
    current = parent;
  }
}

/**
 * Decide what the hook file should look like after the install. Three
 * branches:
 *
 *   - `'already-installed'`, the existing file already carries the
 *     skill-map marker. Caller no-ops.
 *   - `'fresh'`            , no existing hook; write the full body
 *     with shebang + skill-map block.
 *   - `'chained'`          , existing hook without marker; append the
 *     skill-map block (preserving the user's content). If the existing
 *     content has no trailing newline, one is added before the block.
 */
function computePlannedHookContent(
  existing: string | null,
):
  | { kind: 'already-installed'; content: string }
  | { kind: 'fresh' | 'chained'; content: string } {
  if (existing === null) return { kind: 'fresh', content: FRESH_HOOK_BODY };
  if (existing.includes(SKILL_MAP_MARKER)) {
    return { kind: 'already-installed', content: existing };
  }
  const sep = existing.endsWith('\n') ? '' : '\n';
  return { kind: 'chained', content: existing + sep + '\n' + SKILL_MAP_BLOCK };
}

/**
 * Make sure the hook is executable. We OR in `0o111` so any existing
 * permission bits the user set survive (e.g. group / other read).
 * Best-effort: on platforms without POSIX permission semantics
 * (Windows) `chmod` is a no-op, which is the desired behaviour.
 */
async function ensureExecutableBit(path: string): Promise<void> {
  const mode = (await stat(path)).mode;
  await chmod(path, mode | 0o111);
}

export const HOOKS_COMMANDS = [HooksInstallCommand];
