/**
 * `sm plugins create <plugin-id>`, scaffold a new plugin directory.
 *
 * Non-interactive Phase 5 minimum: emit a complete `plugin.json` with
 * a placeholder extractor that declares one view contribution (slot
 * `card.footer.left`) and one setting (`string-list`), plus a stub
 * `extensions/extractor.js` and a `README.md`. The author edits to
 * taste.
 *
 * Lands the plugin under `<scope>/.skill-map/plugins/<plugin-id>/`
 * (per `AGENTS.md`, "Plugins are scaffolded, not hand-written", the
 * canonical drop-in location). Use `--at <path>` to override.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { Command, Option } from 'clipanion';

import { installedSpecVersion } from '../../../kernel/adapters/plugin-loader.js';
import { sanitizeForTerminal } from '../../../kernel/util/safe-text.js';
import { tx } from '../../../kernel/util/tx.js';
import { PLUGINS_TEXTS } from '../../i18n/plugins.texts.js';
import {
  defaultProjectPluginsDir,
  defaultUserPluginsDir,
} from '../../util/db-path.js';
import { ExitCode } from '../../util/exit-codes.js';
import { defaultRuntimeContext } from '../../util/runtime-context.js';
import { SmCommand } from '../../util/sm-command.js';

export class PluginsCreateCommand extends SmCommand {
  static override paths = [['plugins', 'create']];
  static override usage = Command.Usage({
    category: 'Plugins',
    description: 'Scaffold a new plugin directory.',
    details:
      'Emits plugin.json + extension stub + README. Pre-filled with one view contribution (slot `card.footer.left`) and one setting (`string-list`); edit to taste. Use `sm plugins slots list` to see other options.',
  });

  pluginId = Option.String({ required: true, name: 'plugin-id' });
  at = Option.String('--at', { required: false });
  force = Option.Boolean('--force', false);

  protected async run(): Promise<number> {
    const ansi = this.ansiFor('stderr');
    const errGlyph = ansi.red('✕');
    if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(this.pluginId)) {
      this.printer!.error(
        tx(PLUGINS_TEXTS.createInvalidId, {
          glyph: errGlyph,
          id: sanitizeForTerminal(this.pluginId),
        }),
      );
      return ExitCode.Error;
    }
    const ctx = defaultRuntimeContext();
    const baseDir = this.global
      ? defaultUserPluginsDir(ctx)
      : defaultProjectPluginsDir(ctx);
    const targetDir = this.at ? resolve(this.at) : join(baseDir, this.pluginId);
    if (existsSync(targetDir) && !this.force) {
      this.printer!.error(
        tx(PLUGINS_TEXTS.createRefuseOverwrite, {
          glyph: errGlyph,
          targetDir: sanitizeForTerminal(targetDir),
        }),
      );
      return ExitCode.Error;
    }
    mkdirSync(join(targetDir, 'extensions'), { recursive: true });

    const specVersion = installedSpecVersion();
    const manifest = {
      id: this.pluginId,
      version: '0.1.0',
      specCompat: `^${specVersion}`,
      catalogCompat: '^1.0.0',
      extensions: ['./extensions/extractor.js'],
      description: 'Generated by `sm plugins create`. Edit to taste.',
      settings: {
        keywords: {
          type: 'string-list',
          label: 'Keywords to track',
          description: 'Words counted across each scanned node body.',
          default: ['TODO', 'FIXME'],
          min: 1,
        },
      },
    };
    writeFileSync(
      join(targetDir, 'plugin.json'),
      JSON.stringify(manifest, null, 2) + '\n',
    );

    writeFileSync(
      join(targetDir, 'extensions', 'extractor.js'),
      scaffolderExtractorStub(this.pluginId),
    );
    writeFileSync(join(targetDir, 'README.md'), scaffolderReadme(this.pluginId));

    this.printer!.data(
      tx(PLUGINS_TEXTS.createSuccess, {
        targetDir: sanitizeForTerminal(targetDir),
        pluginId: this.pluginId,
      }),
    );
    return ExitCode.Ok;
  }
}

function scaffolderExtractorStub(pluginId: string): string {
  return `/**
 * Generated by \`sm plugins create\`. Edit the extract() body.
 *
 * Loader contract: the plugin loader resolves the extension via the
 * MODULE'S DEFAULT EXPORT (\`export default { ... }\`). Renaming or
 * splitting into a named export will surface as \`load-error: default
 * export missing a string \\\`kind\\\` field\`.
 *
 * Declared view contributions (in plugin.json):
 *   - 'count' → slot \`card.footer.left\` (renders as a chip
 *     in the left footer of the node card)
 *
 * Declared settings:
 *   - 'keywords' (string-list) → exposed as ctx.settings.keywords
 *
 * See: spec/plugin-author-guide.md §View contributions
 *      spec/view-slots.md
 */
export default {
  id: '${pluginId}-extractor',
  pluginId: '${pluginId}',
  kind: 'extractor',
  version: '0.1.0',
  description: 'Counts configured keywords per node.',
  stability: 'experimental',
  mode: 'deterministic',
  emitsLinkKinds: [],
  defaultConfidence: 'high',
  scope: 'body',

  viewContributions: {
    count: {
      slot: 'card.footer.left',
      icon: '🔍',
      label: 'kw',
      emitWhenEmpty: false,
    },
  },

  extract(ctx) {
    const keywords = (ctx.settings && ctx.settings.keywords) || ['TODO', 'FIXME'];
    let total = 0;
    for (const kw of keywords) {
      const re = new RegExp('\\\\b' + kw.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&') + '\\\\b', 'gi');
      total += (ctx.body.match(re) || []).length;
    }
    if (total > 0) {
      ctx.emitContribution('count', { value: total });
    }
  },
};
`;
}

function scaffolderReadme(pluginId: string): string {
  return `# ${pluginId}

Generated by \`sm plugins create\`. Edit \`extensions/extractor.js\` to taste.

## Verbs

- \`sm plugins show ${pluginId}\`: manifest + load status
- \`sm plugins doctor\`: full plugin diagnostic
- \`sm scan\`: re-emit contributions

## Resources

- \`spec/plugin-author-guide.md\` §View contributions
- \`spec/view-slots.md\`: the closed catalog of slots
- \`spec/input-types.md\`: the closed catalog of input-types for settings
- \`sm plugins slots list\`: browse the catalog from the CLI
`;
}
