// AUTO-GENERATED by scripts/generate-view-catalog.js. Do not edit by hand.
// Regenerate with `pnpm --filter @skill-map/cli view-catalog`.
// Source of truth: the `oneOf` const lists in
//   spec/schemas/view-slots.schema.json#/$defs/SlotName
//   spec/schemas/input-types.schema.json#/$defs/InputTypeName
// Each summary is the spec description for that slot / input-type.
// Edit the spec, then regenerate. Browse via `sm plugins slots list`.

export const VIEW_SLOTS_CATALOG = [
  { id: 'card.title.right', summary: 'Small icon marker next to the card title (language flag, platform glyph).' },
  { id: 'card.subtitle.left', summary: 'Single non-negative integer in the card subtitle row.' },
  { id: 'card.footer.left', summary: 'Counter chip in the left footer of the card.' },
  { id: 'card.footer.right', summary: 'Counter chip in the right footer of the card.' },
  { id: 'graph.node.alert', summary: 'Reserved corner badge on the graph node, special-case signals only. No core analyzer emits here; routine "this node has a problem" findings belong in `card.footer.right`.' },
  { id: 'inspector.header.badge', summary: 'Unified badge in the inspector header cluster: icon and/or label and/or count, optional severity. Multi-cardinality, priority order, modeled on card.footer.left. Replaces the retired inspector.header.badge.counter and inspector.header.badge.tag sub-slots.' },
  { id: 'inspector.action.button', summary: 'Action button in the inspector\'s generic Actions section. Click dispatches a kernel Action by qualified id via POST /api/actions/:id. Always emitted; the payload `enabled` flag carries the dynamic condition (e.g. isStale for the bump button).' },
  { id: 'inspector.surface.version', summary: 'The node\'s VERSION surface (header version chip + the card\'s vN label). The claiming Action owns the affordance; click dispatches the payload\'s actionId (the bump flow). Single-cardinality logical surface.' },
  { id: 'inspector.surface.stability', summary: 'The node\'s STABILITY surface (header stability chip + card badge). The claiming Action owns the affordance; click opens the payload prompt and dispatches its actionId. Single-cardinality logical surface.' },
  { id: 'inspector.surface.tags', summary: 'The node\'s TAG-ROW surface (inline tag editor + the card\'s tag chips). The claiming Action owns the affordance; edits dispatch the payload\'s actionId. Single-cardinality logical surface.' },
  { id: 'inspector.surface.summary', summary: 'The header\'s semantic-analysis (summarize) affordance. The claiming probabilistic Action owns it; click submits a job for the payload\'s actionId. Single-cardinality logical surface.' },
  { id: 'inspector.surface.auto-tag', summary: 'The tag row\'s auto-tag (sparkles) affordance. The claiming probabilistic Action owns it; click submits a job for the payload\'s actionId. Single-cardinality logical surface.' },
  { id: 'inspector.body.panel.breakdown', summary: 'Top-N labeled values rendered as a bar chart in the inspector body.' },
  { id: 'inspector.body.panel.records', summary: 'Tabular data (rows × columns ≤ 50 × 6) in the inspector body.' },
  { id: 'inspector.body.panel.tree', summary: 'Recursive label/children hierarchy (depth ≤ 6, total ≤ 200) in the inspector body.' },
  { id: 'inspector.body.panel.key-values', summary: 'Flat key/value pairs (≤ 50) in the inspector body.' },
  { id: 'inspector.body.panel.link-list', summary: 'Clickable scope-relative paths (≤ 100) in the inspector body.' },
  { id: 'inspector.body.panel.markdown', summary: 'Sanitized markdown text (≤ 4096 chars) in the inspector body.' },
  { id: 'topbar.nav.start', summary: 'Scope-wide indicator chip at the start of the topbar nav (before the view-switcher links).' },
] as const;

export const INPUT_TYPES_CATALOG = [
  { id: 'string-list', summary: 'Array of free-form strings.' },
  { id: 'single-string', summary: 'Single text input.' },
  { id: 'boolean-flag', summary: 'On/off toggle.' },
  { id: 'integer', summary: 'Integer with optional bounds.' },
  { id: 'number', summary: 'Decimal number with optional bounds.' },
  { id: 'enum-pick', summary: 'Pick one from a closed set.' },
  { id: 'enum-multipick', summary: 'Pick zero or more from a closed set.' },
  { id: 'path-glob', summary: 'Glob pattern (single or multiple).' },
  { id: 'regex', summary: 'ECMAScript regex pattern body.' },
  { id: 'secret', summary: 'Sensitive string, forced into project-local storage (gitignored), not encrypted.' },
  { id: 'key-value-list', summary: 'Editable mapping of strings to strings.' },
  { id: 'match-list', summary: 'List of match entries, each literal (exact equality), regex (unanchored test), or glob (gitignore-style).' },
] as const;
